/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_hetu_omnicache_OMVectorBase */

#ifndef _Included_nova_hetu_omnicache_OMVectorBase
#define _Included_nova_hetu_omnicache_OMVectorBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    get
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_nova_hetu_omnicache_OMVectorBase_get
  (JNIEnv *, jobject);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    mul
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_OMVectorBase_mul
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    mmul
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_OMVectorBase_mmul
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    agg
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_OMVectorBase_agg
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    allocate
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_OMVectorBase_allocate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
