/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_hetu_omnicache_OMVectorBase */

#ifndef _Included_nova_hetu_omnicache_OMVectorBase
#define _Included_nova_hetu_omnicache_OMVectorBase
#ifdef __cplusplus
extern "C" {
#endif
#undef nova_hetu_omnicache_OMVectorBase_INT_DATA_TYPE
#define nova_hetu_omnicache_OMVectorBase_INT_DATA_TYPE 1L
#undef nova_hetu_omnicache_OMVectorBase_LONG_DATA_TYPE
#define nova_hetu_omnicache_OMVectorBase_LONG_DATA_TYPE 2L
#undef nova_hetu_omnicache_OMVectorBase_DOUBLE_DATA_TYPE
#define nova_hetu_omnicache_OMVectorBase_DOUBLE_DATA_TYPE 3L
/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    mul
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_OMVectorBase_mul
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    mmul
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_OMVectorBase_mmul
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    agg
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_OMVectorBase_agg
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    allocate
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_OMVectorBase_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    free
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_OMVectorBase_free
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nova_hetu_omnicache_OMVectorBase
 * Method:    invoke
 * Signature: (Ljava/lang/String;[I[Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_OMVectorBase_invoke
  (JNIEnv *, jclass, jstring, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
