/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_hetu_omnicache_runtime_JniWrapper */

#ifndef _Included_nova_hetu_omnicache_runtime_JniWrapper
#define _Included_nova_hetu_omnicache_runtime_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    compile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_compile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;[IJ[II)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_execute
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jintArray, jlong, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
