/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_hetu_omnicache_runtime_JniWrapper */

#ifndef _Included_nova_hetu_omnicache_runtime_JniWrapper
#define _Included_nova_hetu_omnicache_runtime_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    compile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_compile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeV1
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;J[Ljava/nio/ByteBuffer;J[I[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeV1
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jlong, jobjectArray, jlong, jintArray, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;[IJ[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_execute
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jintArray, jlong, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    getFinalResult
 * Signature: (Ljava/lang/String;[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_getFinalResult
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    filterCompile
 * Signature: (Ljava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_filterCompile
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    filterExecute
 * Signature: (J[JJIJI)I
 */
JNIEXPORT jint JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_filterExecute
  (JNIEnv *, jobject, jlong, jlongArray, jlong, jint, jlong, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    filterFinished
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_filterFinished
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nova_hetu_omniruntime_operator_JniWrapper
 * Method:    createSortOperatorFactory
 * Signature: ([I[I[I[I[I)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omniruntime_operator_JniWrapper_createSortOperatorFactory
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     nova_hetu_omniruntime_operator_JniWrapper
 * Method:    createHashAggregationOperatorFactory
 * Signature: ([I[I[I[I[I[I)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omniruntime_operator_JniWrapper_createHashAggregationOperatorFactory
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     nova_hetu_omniruntime_operator_JniWrapper
 * Method:    createOperator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omniruntime_operator_JniWrapper_createOperator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nova_hetu_omniruntime_operator_JniWrapper
 * Method:    addInput
 * Signature: (JJIJI)I
 */
JNIEXPORT jint JNICALL Java_nova_hetu_omniruntime_operator_JniWrapper_addInput
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     nova_hetu_omniruntime_operator_JniWrapper
 * Method:    getOutput
 * Signature: (J)[Lnova/hetu/omniruntime/operator/OMResult;
 */
JNIEXPORT jobjectArray JNICALL Java_nova_hetu_omniruntime_operator_JniWrapper_getOutput
  (JNIEnv *, jobject, jlong);

  /*
 * Class:     nova_hetu_omniruntime_operator_JniWrapper
 * Method:    close
 * Signature: (J)[Lnova/hetu/omniruntime/operator/void;
 */
JNIEXPORT void JNICALL Java_nova_hetu_omniruntime_operator_JniWrapper_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nova_hetu_omniruntime_vector_OMVectorBase
 * Method:    allocate
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omniruntime_vector_OMVectorBase_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     nova_hetu_omniruntime_vector_OMVectorBase
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omniruntime_vector_OMVectorBase_release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
