/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_hetu_omnicache_runtime_JniWrapper */

#ifndef _Included_nova_hetu_omnicache_runtime_JniWrapper
#define _Included_nova_hetu_omnicache_runtime_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    compile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_compile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeV1
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;J[Ljava/nio/ByteBuffer;J[I[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeV1
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jlong, jobjectArray, jlong, jintArray, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;[IJ[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_execute
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jintArray, jlong, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    getFinalResult
 * Signature: (Ljava/lang/String;[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_getFinalResult
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    prepareAgg
 * Signature: (JIJIIIIIII)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_prepareAgg
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeAggIntermediate
 * Signature: (JJJIJI)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeAggIntermediate
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeAggFinal
 * Signature: (J)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeAggFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    allocAndInitSort
 * Signature: ([II[II[I[I[II)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_allocAndInitSort
  (JNIEnv *, jobject, jintArray, jint, jintArray, jint, jintArray, jintArray, jintArray, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    addTable
 * Signature: (J[J[JJ)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_addTable
  (JNIEnv *, jobject, jlong, jlongArray, jlongArray, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    sort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_sort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    getResult
 * Signature: (J)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_getResult
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
