/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nova_hetu_omnicache_runtime_JniWrapper */

#ifndef _Included_nova_hetu_omnicache_runtime_JniWrapper
#define _Included_nova_hetu_omnicache_runtime_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    compile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_compile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeV1
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;J[Ljava/nio/ByteBuffer;J[I[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeV1
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jlong, jobjectArray, jlong, jintArray, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/nio/ByteBuffer;[IJ[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_execute
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jintArray, jlong, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    getFinalResult
 * Signature: (Ljava/lang/String;[I)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_getFinalResult
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    prepareAgg
 * Signature: (JIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_prepareAgg
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    createOperator
 * Signature: (JIJIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_createOperator
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeAggIntermediate
 * Signature: (JJJIJIJ)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeAggIntermediate
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    executeAggFinal
 * Signature: (J)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_executeAggFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    sortPrepare
 * Signature: ([II[II[I[I[II)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_sortPrepare
  (JNIEnv *, jobject, jintArray, jint, jintArray, jint, jintArray, jintArray, jintArray, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    sortCreateOperator
 * Signature: (J[II[II[I[I[II)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_sortCreateOperator
  (JNIEnv *, jobject, jlong, jintArray, jint, jintArray, jint, jintArray, jintArray, jintArray, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    sortAddInput
 * Signature: (JJ[J[JI[II)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_sortAddInput
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jlongArray, jint, jintArray, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    sortExecute
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_sortExecute
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    sortGetOutput
 * Signature: (JJ)Lnova/hetu/omnicache/runtime/OMResult;
 */
JNIEXPORT jobject JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_sortGetOutput
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    filterCompile
 * Signature: (Ljava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_filterCompile
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    filterExecute
 * Signature: (J[JJIJI)I
 */
JNIEXPORT jint JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_filterExecute
  (JNIEnv *, jobject, jlong, jlongArray, jlong, jint, jlong, jint);

/*
 * Class:     nova_hetu_omnicache_runtime_JniWrapper
 * Method:    filterFinished
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nova_hetu_omnicache_runtime_JniWrapper_filterFinished
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
