/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2023. All rights reserved.
 * Description: Including all aggregator headers
 */
#ifndef OMNI_RUNTIME_ALL_AGGREGATORS_H
#define OMNI_RUNTIME_ALL_AGGREGATORS_H
#include "operator/aggregation/aggregator/only_aggregator_factory.h"
#include "operator/aggregation/aggregator/sum_aggregator.h"
#include "operator/aggregation/aggregator/sum_flatim_aggregator.h"
#include "operator/aggregation/aggregator/sum_spark_decimal_aggregator.h"
#include "operator/aggregation/aggregator/average_aggregator.h"
#include "operator/aggregation/aggregator/average_flatim_aggregator.h"
#include "operator/aggregation/aggregator/average_spark_decimal_aggregator.h"
#include "operator/aggregation/aggregator/stddev_samp_aggregator.h"
#include "operator/aggregation/aggregator/stddev_pop_aggregator.h"
#include "operator/aggregation/aggregator/var_samp_aggregator.h"
#include "operator/aggregation/aggregator/var_pop_aggregator.h"
#include "operator/aggregation/aggregator/min_aggregator.h"
#include "operator/aggregation/aggregator/min_varchar_aggregator.h"
#include "operator/aggregation/aggregator/max_aggregator.h"
#include "operator/aggregation/aggregator/max_varchar_aggregator.h"
#include "operator/aggregation/aggregator/count_column_aggregator.h"
#include "operator/aggregation/aggregator/count_all_aggregator.h"
#include "operator/aggregation/aggregator/mask_column_assistant_aggregator.h"
#include "operator/aggregation/aggregator/typed_mask_column_assistant_aggregator.h"
#include "operator/aggregation/aggregator/first_aggregator.h"
#include "operator/aggregation/aggregator/last_aggregator.h"
#include "operator/aggregation/aggregator/try_sum_flatim_aggregator.h"
#include "operator/aggregation/aggregator/bloom_filter_aggregator.h"
#include "operator/aggregation/aggregator/minby_aggregator.h"
#include "operator/aggregation/aggregator/maxby_aggregator.h"
#include "operator/aggregation/aggregator/bit_and_aggregator.h"
#include "operator/aggregation/aggregator/bit_or_aggregator.h"
#include "operator/aggregation/aggregator/bit_xor_aggregator.h"
#include "operator/aggregation/aggregator/approx_count_distinct_aggregator.h"
#include "operator/aggregation/aggregator/approx_percentile_aggregator.h"
#include "operator/aggregation/aggregator/corr_aggregator.h"
#include "operator/aggregation/aggregator/covar_pop_aggregator.h"
#include "operator/aggregation/aggregator/covar_samp_aggregator.h"
#include "operator/aggregation/aggregator/collect_set_aggregator.h"
#include "operator/aggregation/aggregator/collect_list_aggregator.h"
#include "operator/aggregation/aggregator/kurtosis_aggregator.h"
#include "operator/aggregation/aggregator/skewness_aggregator.h"
#include "operator/aggregation/aggregator/regr_aggregator.h"
#endif // OMNI_RUNTIME_ALL_AGGREGATORS_H
