/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#pragma once

#include "connectors/Connector.h"
#include "type/data_type.h"
#include "type/Subfield.h"
#include <nlohmann/json.hpp>

namespace omniruntime::connector::hive {

using TypedExprPtr = expressions::Expr *;

class HiveColumnHandle : public ColumnHandle {
public:
    enum class ColumnType {
        kPartitionKey,
        kRegular,
        kSynthesized,
        /// A zero-based row number of type BIGINT auto-generated by the connector.
        /// Rows numbers are unique within a single file only.
        kRowIndex,
        kRowId,
    };

    struct ColumnParseParameters {
        enum PartitionDateValueFormat {
            kISO8601,
            kDaysSinceEpoch,
        } partitionDateValueFormat;
    };

    /// NOTE: 'dataType' is the column type in target write table. 'hiveType' is
    /// converted type of the corresponding column in source table which might not
    /// be the same type, and the table scan needs to do data coercion if needs.
    /// The table writer also needs to respect the type difference when processing
    /// input data such as bucket id calculation.
    HiveColumnHandle(
            const std::string& name,
            ColumnType columnType,
            type::DataTypePtr dataType,
            type::DataTypePtr hiveType,
            std::vector<type::Subfield> requiredSubfields = {},
            ColumnParseParameters columnParseParameters = {})
                : name_(name),
                  columnType_(columnType),
                  dataType_(std::move(dataType)),
                  hiveType_(std::move(hiveType)),
                  requiredSubfields_(std::move(requiredSubfields)),
                  columnParseParameters_(columnParseParameters) {
    }

    const std::string& name() const override
    {
        return name_;
    }

    ColumnType columnType() const
    {
        return columnType_;
    }

    const type::DataTypePtr& dataType() const
    {
        return dataType_;
    }

    const type::DataTypePtr& hiveType() const
    {
        return hiveType_;
    }

    /// Applies to columns of complex types: arrays, maps and structs.  When a
    /// query uses only some of the subfields, the engine provides the complete
    /// list of required subfields and the connector is free to prune the rest.
    /// Examples:
    ///  - SELECT a[1], b['x'], x.y FROM t
    ///  - SELECT a FROM t WHERE b['y'] > 10
    /// Pruning a struct means populating some of the members with null values.
    /// Pruning a map means dropping keys not listed in the required subfields.
    /// Pruning arrays means dropping values with indices larger than maximum
    /// required index.
    const std::vector<type::Subfield>& requiredSubfields() const
    {
        return requiredSubfields_;
    }

    bool isPartitionKey() const
    {
        return columnType_ == ColumnType::kPartitionKey;
    }

    bool isPartitionDateValueDaysSinceEpoch() const
    {
        return columnParseParameters_.partitionDateValueFormat ==
               ColumnParseParameters::kDaysSinceEpoch;
    }

    std::string toString() const;

    static ColumnHandlePtr create(const nlohmann::json& obj);

    static std::string columnTypeName(HiveColumnHandle::ColumnType columnType);

    static HiveColumnHandle::ColumnType columnTypeFromName(
            const std::string& name);

    static void registerSerDe();

private:
    const std::string name_;
    const ColumnType columnType_;
    const type::DataTypePtr dataType_;
    const type::DataTypePtr hiveType_;
    const std::vector<type::Subfield> requiredSubfields_;
    const ColumnParseParameters columnParseParameters_;
};

class HiveTableHandle : public ConnectorTableHandle {
public:
    HiveTableHandle(
            std::string connectorId,
            const std::string& tableName,
            bool filterPushdownEnabled,
            std::string enhancementJson,
            const type::RowTypePtr& dataColumns = nullptr,
            const std::unordered_map<std::string, std::string>& tableParameters = {});


    const std::string& tableName() const
    {
        return tableName_;
    }

    const std::string& name() const
    {
        return tableName();
    }

    bool isFilterPushdownEnabled() const
    {
        return filterPushdownEnabled_;
    }

    // Schema of the table.  Need this for reading TEXTFILE.
    const type::RowTypePtr& dataColumns() const
    {
        return dataColumns_;
    }

    const std::unordered_map<std::string, std::string>& tableParameters() const
    {
        return tableParameters_;
    }

    static ConnectorTableHandlePtr create(
            const nlohmann::json& obj,
            void* context);

    static void registerSerDe();

    const std::string& GetEnhancementJson() const
    {
        return enhancementJson_;
    }

private:
    const std::string tableName_;
    const bool filterPushdownEnabled_;
    const type::RowTypePtr dataColumns_;
    const std::unordered_map<std::string, std::string> tableParameters_;
    const std::string enhancementJson_;
};

} // namespace omniruntime::connector::hive
