/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2022. All rights reserved.
 * Description: Batch util Function Registry
 */
#include "batch_func_registry_util.h"
#include "batch_functions/batch_utilfunctions.h"

using namespace omniruntime;
using namespace omniruntime::type;

std::vector<Function> BatchUtilFunctionRegistry::GetFunctions()
{
    std::vector<Function> utilFnRegistry = {
            Function(reinterpret_cast<void *>(fillRowIndexArray), "fill_rowIdx", {}, { OMNI_INT, OMNI_INT },
                     OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillBool), "batch_fill_literal", {},
                     {OMNI_BOOLEAN},OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillInt32), "batch_fill_literal", {}, { OMNI_INT},
                     OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillInt64), "batch_fill_literal", {}, { OMNI_LONG},
                     OMNI_LONG, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillDecimal128), "batch_fill_literal", {}, { OMNI_DECIMAL128 },
                     OMNI_DECIMAL128, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillInt64), "batch_fill_literal", {}, { OMNI_DECIMAL64},
                     OMNI_DECIMAL64, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillDouble), "batch_fill_literal", {}, { OMNI_DOUBLE},
                     OMNI_DOUBLE, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillString), "batch_fill_literal", {}, { OMNI_CHAR},
                     OMNI_CHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillString), "batch_fill_literal", {}, { OMNI_VARCHAR},
                     OMNI_VARCHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(fillLength), "batch_fill_length", {}, { OMNI_INT },
                     OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyInt32), "batch_copy", {}, { OMNI_INT},
                     OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyInt64), "batch_copy", {}, { OMNI_LONG},
                     OMNI_LONG, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyDecimal128), "batch_copy", {}, { OMNI_DECIMAL128 },
                     OMNI_DECIMAL128, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyInt64), "batch_copy", {}, { OMNI_DECIMAL64},
                     OMNI_DECIMAL64, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyDouble), "batch_copy", {}, { OMNI_DOUBLE },
                     OMNI_DOUBLE, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyBoolean), "batch_copy", {}, { OMNI_BOOLEAN },
                     OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyString), "batch_copy", {}, { OMNI_VARCHAR },
                     OMNI_VARCHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(copyString), "batch_copy", {}, { OMNI_CHAR },
                     OMNI_CHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createNot), "batch_not", {}, { OMNI_BOOLEAN },
            OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createAnd), "batch_and", {}, {OMNI_BOOLEAN, OMNI_BOOLEAN},
                     OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createOr), "batch_or", {}, {OMNI_BOOLEAN, OMNI_BOOLEAN},
                     OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createAndNot), "batch_and_not", {},
                     {OMNI_BOOLEAN, OMNI_BOOLEAN, OMNI_INT, OMNI_INT},
                     OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createAndNotBool), "batch_and_not", {},
                     {OMNI_BOOLEAN, OMNI_BOOLEAN},
                     OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createOrExpr), "batch_or_expr", {},
                     {OMNI_BOOLEAN, OMNI_BOOLEAN},
                     OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(createAndExpr), "batch_and_expr", {},
                     {OMNI_BOOLEAN, OMNI_BOOLEAN},
                     OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),

            Function(reinterpret_cast<void *>(ifExpr<bool>), "batch_if", {},
                     {OMNI_BOOLEAN},OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExpr<int32_t>), "batch_if", {},
                     {OMNI_INT},OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExpr<int64_t>), "batch_if", {},
                     {OMNI_LONG},OMNI_LONG, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExpr<double>), "batch_if", {},
                     {OMNI_DOUBLE},OMNI_DOUBLE, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExprStr), "batch_if", {},
                     {OMNI_VARCHAR},OMNI_VARCHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExprStr), "batch_if", {},
                     {OMNI_CHAR},OMNI_CHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExprDecimal<int64_t>), "batch_if", {},
                     {OMNI_DECIMAL64},OMNI_DECIMAL64, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(ifExprDecimal<Decimal128>), "batch_if", {},
                     {OMNI_DECIMAL128},OMNI_DECIMAL128, NULL_RESULT_IF_ANY_NULL_ARG),

            Function(reinterpret_cast<void *>(switchExpr<bool>), "batch_switch", {},
                     {OMNI_BOOLEAN},OMNI_BOOLEAN, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExpr<int32_t>), "batch_switch", {},
                     {OMNI_INT},OMNI_INT, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExpr<int64_t>), "batch_switch", {},
                     {OMNI_LONG},OMNI_LONG, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExpr<double>), "batch_switch", {},
                     {OMNI_DOUBLE},OMNI_DOUBLE, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExprString), "batch_switch", {},
                     {OMNI_CHAR},OMNI_CHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExprString), "batch_switch", {},
                     {OMNI_VARCHAR},OMNI_VARCHAR, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExprDecimal<int64_t>), "batch_switch", {},
                     {OMNI_DECIMAL64},OMNI_DECIMAL64, NULL_RESULT_IF_ANY_NULL_ARG),
            Function(reinterpret_cast<void *>(switchExprDecimal<Decimal128>), "batch_switch", {},
                     {OMNI_DECIMAL128},OMNI_DECIMAL128, NULL_RESULT_IF_ANY_NULL_ARG),
    };

    return utilFnRegistry;
}
