/*
 * @Copyright: Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * @Description: FunctionType enum
 */

#ifndef OMNI_RUNTIME_FUNCTION_TYPE_H
#define OMNI_RUNTIME_FUNCTION_TYPE_H

namespace omniruntime {
namespace op {
using FunctionType = enum FunctionType {
    OMNI_AGGREGATION_TYPE_SUM = 0,
    OMNI_AGGREGATION_TYPE_COUNT_COLUMN,
    OMNI_AGGREGATION_TYPE_COUNT_ALL,
    OMNI_AGGREGATION_TYPE_AVG,
    OMNI_AGGREGATION_TYPE_MAX,
    OMNI_AGGREGATION_TYPE_MIN,
    OMNI_AGGREGATION_TYPE_DNV,
    OMNI_AGGREGATION_TYPE_FIRST_IGNORENULL,
    OMNI_AGGREGATION_TYPE_FIRST_INCLUDENULL,
    OMNI_AGGREGATION_TYPE_INVALIDE,
    OMNI_WINDOW_TYPE_ROW_NUMBER,
    OMNI_WINDOW_TYPE_RANK
};
}
}
#endif // OMNI_RUNTIME_FUNCTION_TYPE_H
